# -*- coding: utf-8 -*-
"""LanguageTranslation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_W8HtT2lpzI3NqZVBiYZpJ4iL17sHIb
"""

# Install the necessary libraries
!pip install transformers ipywidgets

# Import the required libraries
import ipywidgets as widgets
from transformers import pipeline

# Define a list of languages for dropdown options
languages = ["en", "fr", "de", "es", "it", "pt", "ro", "nl", "pl", "ru", "zh", "ja", "ar"]

# Create dropdown widgets for selecting input and output languages
input_lang_dropdown = widgets.Dropdown(
    options=languages,
    value='en',
    description='Input Lang:',
)

output_lang_dropdown = widgets.Dropdown(
    options=languages,
    value='fr',
    description='Output Lang:',
)

# Create a text box for input text
input_text_box = widgets.Textarea(
    value='',
    placeholder='Enter text to translate...',
    description='Input Text:',
    layout=widgets.Layout(width="500px", height="100px")
)

# Create a button for performing the translation
translate_button = widgets.Button(description="Translate")

# Create a text box to display the output text (translated text)
output_text_box = widgets.Textarea(
    value='',
    placeholder='Translated text will appear here...',
    description='Output Text:',
    disabled=True,
    layout=widgets.Layout(width="500px", height="100px")
)

# Define the translation function
def translate_text(change):
    input_lang = input_lang_dropdown.value
    output_lang = output_lang_dropdown.value
    input_text = input_text_box.value

    # Load the appropriate model based on selected languages
    model_name = f"Helsinki-NLP/opus-mt-{input_lang}-{output_lang}"
    translator = pipeline("translation", model=model_name)

    # Perform translation
    translated_text = translator(input_text)[0]['translation_text']

    # Display the translated text in the output text box
    output_text_box.value = translated_text

# Bind the translate button to the translation function
translate_button.on_click(translate_text)

# Display the UI components (dropdowns, input box, button, and output box)
widgets.VBox([input_lang_dropdown, output_lang_dropdown, input_text_box, translate_button, output_text_box])

